docs(queries): update filter, pagination and sorting details for assorted queries
nckhell/awell-developers pull request #99
Opened 2023-02-06 22:00 UTC by rahulkeerthi

Changes:
- add search filter details to `get patients` query
- update details of pagination and sorting for `get patients`, `search activities`, `get pathways`

2023-02-07 12:12 UTC, nckhell requested changes

2023-02-07 12:12 UTC, nckhell commented on content/awell-orchestration/api-reference/queries/get-pathways.mdx
> +Pagination and sorting are required for this query. If no pagination values are supplied, the API will return only the first 10 care flows, or 10 care flows from any specified offset.
[C] We need to make sure this is listed as a breaking change in the corresponding changelog. Can you create a placeholder for the corresponding release page in the changelog as well as part of this MR?

2023-02-07 12:12 UTC, nckhell commented on content/awell-orchestration/api-reference/queries/get-patients.mdx
> +Pagination and sorting are required for this query. If no pagination values are supplied, the API will return only the first 10 patients, or 10 patients from the specified offset.
Same comment: make sure it is listed as a breaking change on changelog page.

2023-02-07 12:12 UTC, nckhell commented on content/awell-orchestration/api-reference/queries/search-activities.mdx
> +Pagination and sorting are required for this query. If no pagination values are supplied, the API will return only the first 10 activities, or 10 activities from the specified offset.
Same comment.

2023-02-09 10:46 UTC, nckhell commented
@rahulkeerthi Do you make sure to update this MR and address the comment made here in Github and [here](https://gitlab.com/awellhealth/awell-next/-/merge_requests/2677/)?

2023-02-09 14:24 UTC, rahulkeerthi commented
@nckhell changes made, i've set it as release v1.20.6 (which is Monday's release)

2023-02-09 15:10 UTC, nckhell approved these changes

2023-02-13 23:11 UTC, nckhell commented
@rahulkeerthi can you merge this?

2023-02-17 09:50 UTC, nckhell approved these changes

2023-02-17 13:31 UTC, merged